# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gyrokubeoidcfdj < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://example.com/"
  version "0.9.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deepanjan90/kube-oidc-dj/releases/download/v0.9.0/kube-oidc-dj_0.9.0_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d21e53f1ab51cc858e8e147f76557150a72a10d9b387bf0f92869a730844098c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/deepanjan90/kube-oidc-dj/releases/download/v0.9.0/kube-oidc-dj_0.9.0_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "90f568231279c4c01159edab84053890c9cc57852a305264167d721745a2a8f6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/deepanjan90/kube-oidc-dj/releases/download/v0.9.0/kube-oidc-dj_0.9.0_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "32e38f1baf3c9271523b8078ffcc79c5e55674da561a521ac325ca1764e865ea"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deepanjan90/kube-oidc-dj/releases/download/v0.9.0/kube-oidc-dj_0.9.0_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "fee0e8701849c9c17ef1d95769065d105fb8fd85830d6794f8be9112d54bffb2"
    end
  end

  depends_on "argoproj/tap/kubectl-argo-rollouts"
  depends_on "awscli"
  depends_on "kubectl"
  depends_on "kubectx"
  depends_on "aws-iam-authenticator"
  depends_on "helm"
  depends_on "helmfile"
  depends_on "linkerd"
  depends_on "gettext"
  depends_on "jq"
  depends_on "python-yq"
  depends_on "sops"
  depends_on "direnv"
  depends_on "kube-ps1"
  depends_on "calicoctl"
  depends_on "int128/kubelogin/kubelogin"
  depends_on "git"
  depends_on "zsh" => :optional

  def install
    bin.install "kube-oidc-dj" => "kube-oidc-dj"
  end

  def caveats; <<~EOS
    Use kube-oidc-dj --getToken to generate token to authenticate to an kubernetes cluster
  EOS
  end
end
